export const products = [
  // {
  //   id: 1,
  //   name: "Orange Amnesia",
  //   image: "/images/orangeamnesia.jpeg",
  //   thc: 24,
  //   sativa: 70,
  //   indica: 30,
  //   price: 90,
  //   isNewArrival: true,
  //   isBestSeller: false,
  //   isPromotion: false,
  //   rating: 4.8,
  //   reviews: 128,
  //   stock: 25,
  //   details:
  //     "A potent sativa-dominant strain known for its citrusy aroma and energizing effects.",
  // },
  // {
  //   id: 2,
  //   name: "Milk Monkey",
  //   image: "/images/milkmonkey.jpeg",
  //   thc: 30,
  //   sativa: 40,
  //   indica: 60,
  //   price: 90,
  //   isNewArrival: false,
  //   isBestSeller: false,
  //   isPromotion: false,
  //   effects: ["energetic", "creative", "uplifted"],
  //   flavors: ["cheese", "chemical"],
  //   rating: 4.8,
  //   reviews: 128,
  //   stock: 50,
  //   details: "A creamy hybrid strain with calming effects.",
  // },
  {
    id: 3,
    name: "Velvet Moon",
    image: "/images/velvetmoon.avif",
    thc: 27,
    sativa: 30,
    indica: 70,
    price: 100,
    isNewArrival: false,
    isBestSeller: true,
    isPromotion: false,
    effects: ["euphoric", "relaxed", "sleepy"],
    flavors: ["grape", "berry", "vanilla"],
    rating: 4.8,
    reviews: 128,
    stock: 10,
    details:
      "A smooth indica-dominant strain with deep purple buds and calming effects.✨",
  },
  // {
  //   id: 4,
  //   name: "Rainbow Reserve",
  //   image: "/images/rainbowreserve.png",
  //   thc: 27,
  //   sativa: 50,
  //   indica: 50,
  //   price: 120,
  //   isNewArrival: false,
  //   isBestSeller: true,
  //   isPromotion: false,
  //   rating: 5,
  //   reviews: 4,
  //   stock: 50,
  //   details:
  //     "A smooth indica-dominant strain with deep purple buds and calming effects.✨",
  // },
  {
    id: 5,
    name: "OG Diesel 10g",
    image: "/images/ogdiesel.jpeg",
    thc: 25,
    sativa: 40,
    indica: 60,
    price: 100,
    isNewArrival: false,
    isBestSeller: false,
    isPromotion: false,
    effects: ["euphoric", "energetic", "focused"],
    flavors: ["diesel", "citrus", "earthy"],
    rating: 5,
    reviews: 4,
    stock: 50,
    details: "Potent hybrid with diesel aroma and euphoric effects.",
  },
  {
    id: 6,
    name: "Do Si Dos",
    image: "/images/dosidos.jpeg",
    thc: 29,
    sativa: 30,
    indica: 70,
    price: 80,
    isNewArrival: false,
    isBestSeller: false,
    isPromotion: false,
    effects: ["euphoric", "relaxed", "sleepy"],
    flavors: ["sweet", "earthy", "floral"],
    rating: 5,
    reviews: 4,
    stock: 50,
    details:
      "A smooth indica-dominant strain with deep purple buds and calming effects.✨",
  },
  // {
  //   id: 7,
  //   name: "Epic Buzz",
  //   image: "/images/epicbuzz.jpeg",
  //   thc: 29,
  //   sativa: 50,
  //   indica: 50,
  //   price: 90,
  //   isNewArrival: false,
  //   isBestSeller: false,
  //   isPromotion: false,
  //   rating: 5,
  //   reviews: 4,
  //   stock: 5,
  //   details:
  //     "A perfectly balanced hybrid strain offering an energetic head high with full-body relaxation.✨",
  // },
  // {
  //   id: 8,
  //   name: "Rainbow Cake",
  //   image: "/images/rainbowcake.jpeg",
  //   thc: 30,
  //   sativa: 70,
  //   indica: 30,
  //   price: 80,
  //   isNewArrival: true,
  //   isBestSeller: false,
  //   isPromotion: false,
  //   isComingSoon: false,
  //   rating: 5,
  //   reviews: 4,
  //   stock: 25,
  //   details:
  //     "A sweet, fruity sativa that uplifts mood and sparks creativity.✨",
  // },
  // {
  //   id: 9,
  //   name: "Cap Junky",
  //   image: "/images/capjunky.jpeg",
  //   thc: 33,
  //   sativa: 10,
  //   indica: 90,
  //   price: 90,
  //   isNewArrival: false,
  //   isBestSeller: true,
  //   isPromotion: false,
  //   isComingSoon: false,
  //   effects: ["giggly", "tingly", "relaxed"],
  //   flavors: ["apricot", "apple", "mint"],
  //   rating: 5,
  //   reviews: 4,
  //   stock: 25,
  //   details:
  //     "A potent indica strain delivering deep relaxation and powerful sedative effects.✨",
  // },
  // {
  //   id: 10,
  //   name: "Truffle Aloha",
  //   image: "/images/trufflealoha.jpeg",
  //   thc: 28,
  //   sativa: 70,
  //   indica: 30,
  //   price: 40,
  //   isNewArrival: false,
  //   isBestSeller: true,
  //   isPromotion: false,
  //   isComingSoon: false,
  //   effects: ["energetic", "creative", "uplifted"],
  //   flavors: ["citrus", "tropical", "pineapple"],
  //   rating: 5,
  //   reviews: 4,
  //   stock: 7,
  //   details:
  //     "A tropical sativa-dominant hybrid with sweet truffle undertones, delivering an uplifting and energetic high.✨",
  // },
  // {
  //   id: 11,
  //   name: "Sugar Baby Exotic",
  //   image: "/images/sugarbaby.jpeg",
  //   thc: 33,
  //   sativa: 10,
  //   indica: 90,
  //   price: 80,
  //   isNewArrival: false,
  //   isBestSeller: false,
  //   isPromotion: false,
  //   isComingSoon: false,
  //   effects: ["sleepy", "relaxed", "euphoric"],
  //   flavors: ["sweet", "berry", "vanilla"],
  //   rating: 5,
  //   reviews: 4,
  //   stock: 50,
  //   details:
  //     "A potent indica-dominant strain with sweet berry notes, perfect for deep relaxation and peaceful sleep.✨",
  // },
  {
    id: 12,
    name: "White Fire Punch",
    image: "/images/whitefire.jpeg",
    thc: 29,
    sativa: 20,
    indica: 80,
    price: 70,
    isNewArrival: false,
    isBestSeller: true,
    isPromotion: false,
    isComingSoon: false,
    effects: ["relaxed", "sleepy", "euphoric"],
    flavors: ["sweet", "berry", "vanilla"],
    rating: 5,
    reviews: 4,
    stock: 10,
    details:
      "A potent indica-dominant strain with sweet berry notes, perfect for deep relaxation and peaceful sleep.✨",
  },
  {
    id: 13,
    name: "Amnesia Lemon ",
    image: "/images/amnesialemon.jpeg",
    thc: 27,
    sativa: 50,
    indica: 50,
    price: 50,
    isNewArrival: false,
    isBestSeller: true,
    isPromotion: false,
    isComingSoon: false,
    effects: ["energetic", "focused", "uplifted"],
    flavors: ["lemon", "sweet", "earthy"],
    rating: 5,
    reviews: 4,
    stock: 25,
    details:
      "A balanced strain with lemony flavors, ideal for energizing and uplifting experiences.✨",
  },
  {
    id: 14,
    name: "Pineapple Express 2",
    image: "/images/pineapple.jpeg",
    thc: 29,
    sativa: 20,
    indica: 80,
    price: 50,
    isNewArrival: false,
    isBestSeller: false,
    isPromotion: false,
    isComingSoon: false,
    effects: ["relaxed", "sleepy", "euphoric"],
    flavors: ["pineapple", "tropical", "citrus"],
    rating: 5,
    reviews: 4,
    stock: 25,
    details:
      "A tropical indica-dominant strain with pineapple flavors, ideal for relaxation and euphoria.✨",
  },
  {
    id: 15,
    name: "Sapphire OG",
    image: "/images/sapphireog.jpeg",
    thc: 25,
    sativa: 20,
    indica: 80,
    price: 120,
    isNewArrival: true,
    isBestSeller: true,
    isPromotion: false,
    isComingSoon: false,
    effects: ["relaxed", "sleepy", "euphoric"],
    flavors: ["earthy", "sweet", "floral"],
    rating: 5,
    reviews: 4,
    stock: 30,
    details:
      "A tropical indica-dominant strain with pineapple flavors, ideal for relaxation and euphoria.✨",
  },
  {
    id: 16,
    name: "Hippie Berry",
    image: "/images/hippie.jpeg",
    thc: 33,
    sativa: 70,
    indica: 30,
    price: 90,
    isNewArrival: true,
    isBestSeller: true,
    isPromotion: false,
    isComingSoon: false,
    effects: ["energetic", "happy", "talkative"],
    flavors: ["berry", "tropical"],
    rating: 5,
    reviews: 4,
    stock: 25,
    details:
      "A sativa-dominant strain with berry flavors, perfect for energetic and happy vibes.✨",
  },
  {
    id: 17,
    name: "Space Candy",
    image: "/images/spacecandy.jpeg",
    thc: 31,
    sativa: 50,
    indica: 50,
    price: 80,
    isNewArrival: true,
    isBestSeller: false,
    isPromotion: false,
    isComingSoon: false,
    effects: ["relaxed", "relieve", "euphoric"],
    flavors: ["sweet", "fruity", "tropical"],
    rating: 5,
    reviews: 4,
    stock: 25,
    details:
      "A balanced hybrid strain with sweet and fruity flavors, perfect for relaxation and euphoria.✨",
  },
  {
    id: 18,
    name: "Pop Deluxe Black",
    image: "/images/deluxe.jpeg",
    thc: 32,
    sativa: 30,
    indica: 70,
    price: 70,
    isNewArrival: true,
    isBestSeller: false,
    isPromotion: false,
    isComingSoon: false,
    effects: ["relaxed", "focused", "euphoric"],
    flavors: ["blackberry", "cherry", "lemon"],
    rating: 5,
    reviews: 4,
    stock: 25,
    details:
      "A potent indica-dominant strain with blackberry, cherry, and lemon flavors, perfect for relaxation and euphoria.✨",
  },
  {
    id: 19,
    name: "Black Berry",
    image: "/images/blackberry.jpeg",
    thc: 27,
    sativa: 20,
    indica: 80,
    price: 120,
    isNewArrival: true,
    isBestSeller: true,
    isPromotion: false,
    isComingSoon: false,
    effects: ["relaxed", "sleepy", "euphoric"],
    flavors: ["sweet", "berry", "fruity"],
    rating: 5,
    reviews: 4,
    stock: 25,
    details:
      "An indica-dominant strain with blackberry flavors, ideal for relaxation and euphoria.✨",
  },
  // Add more products as needed
];
